# -*- mode: ruby -*-
# vi: set ft=ruby :

# import yaml defs
require 'yaml'

# pull in yaml configs from groupvars/all
current_dir = File.dirname(File.expand_path(__FILE__))
yamlcfg = YAML.load_file("#{current_dir}/../ansible/envs/dev.yml")

# Specify Vagrant version and Vagrant API version
Vagrant.require_version ">= 1.6.0"
VAGRANTFILE_API_VERSION = "2"

# Create and configure the VM(s)
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Assign a friendly name to this host VM
  config.vm.hostname = "docker-host"

  # Skip checking for an updated Vagrant box
  config.vm.box_check_update = false

  # Always use Vagrant's default insecure key
  config.ssh.insert_key = true
  config.ssh.username = 'docker'
  config.ssh.password = 'tcuser'

  # Spin up a "host box" for use with the Docker provider
  # and then provision it with Docker
  config.vm.box = "hashicorp/boot2docker"
  config.vm.provision "docker"

  # Disable synced folders (prevents an NFS error on "vagrant up")
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.network "private_network", ip: yamlcfg['dockerhost']
end
